version: "3"

tasks:
  # Run arbitrary commands in frontend/backend directories
  frontend:
    desc: Run arbitrary command in frontend directory
    dir: frontend
    cmds:
      - "{{.CLI_ARGS}}"

  backend:
    desc: Run arbitrary command in backend directory
    dir: backend
    cmds:
      - "{{.CLI_ARGS}}"

  # Frontend tasks
  frontend:format:
    desc: Format frontend code
    dir: frontend
    cmds:
      - pnpm run format

  frontend:lint:
    desc: Lint frontend code
    dir: frontend
    cmds:
      - pnpm run lint:fix

  frontend:format-check:
    desc: Check frontend code formatting
    dir: frontend
    cmds:
      - pnpm run format:check

  frontend:lint-check:
    desc: Check frontend code linting
    dir: frontend
    cmds:
      - pnpm run lint

  frontend:type-check:
    desc: Check frontend types
    dir: frontend
    cmds:
      - pnpm run check-types

  frontend:test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - pnpm run test

  # Backend tasks
  backend:format:
    desc: Format backend code
    dir: backend
    cmds:
      - .venv/bin/ruff format .

  backend:lint:
    desc: Lint backend code
    dir: backend
    cmds:
      - .venv/bin/ruff check .

  backend:fix:
    desc: Fix backend code issues
    dir: backend
    cmds:
      - .venv/bin/ruff check . --fix

  backend:format-check:
    desc: Check backend code formatting
    dir: backend
    cmds:
      - .venv/bin/ruff format . --check

  backend:lint-check:
    desc: Check backend code linting
    dir: backend
    cmds:
      - .venv/bin/ruff check .

  backend:test:
    desc: Run backend tests
    dir: backend
    cmds:
      - .venv/bin/pytest -v

  # Combined tasks
  format:
    desc: Format all code (frontend + backend)
    deps:
      - frontend:format
      - backend:format

  lint:
    desc: Lint all code (frontend + backend)
    deps:
      - frontend:lint
      - backend:fix

  format-check:
    desc: Check all code formatting
    deps:
      - frontend:format-check
      - backend:format-check

  lint-check:
    desc: Check all code linting
    deps:
      - frontend:lint-check
      - backend:lint-check

  type-check:
    desc: Check all types
    cmds:
      - task: frontend:type-check

  test:
    desc: Run all tests
    deps:
      - frontend:test
      - backend:test

  # Pre-commit equivalent
  pre-commit:
    desc: Run pre-commit checks (format + lint)
    deps:
      - format
      - lint

  # Pre-push equivalent
  pre-push:
    desc: Run pre-push checks (format-check + lint-check + type-check + test)
    cmds:
      - task: format-check
      - task: lint-check
      - task: type-check
      # - task: test

  # Utility tasks
  check:
    desc: Run all checks (same as pre-push)
    cmds:
      - task: pre-push
